import type { Metadata } from "next";
import "./globals.css";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <header className={styles.header}>
          <div className={styles.logo}>
            <div className={styles.logoDot} />
            <h1 className={styles.logoTitle}>Poker Scrum</h1>
          </div>

          <nav className={styles.nav}>
            <a href="#" className={styles.navLink}>
              Home
            </a>
            <a href="#" className={styles.navLink}>
              About
            </a>
            <a href="#" className={styles.navLink}>
              Contact
            </a>
          </nav>

          <div className={styles.actions}>
            <button className={styles.inviteButton}>Invite players</button>
            <button className={styles.settingsButton}>
              <span className="text-sm font-bold">⚙️</span>
            </button>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
